### ISSUE TITLE
what repos shoud have gpgcheck=1 

### ISSUE THREAD

**Issue by sergiomb2** [rpmfusion-infra/mock-rpmfusion#13]
Hi, in these templates [1] what repos should have gpgcheck=1  and gpgkey=file://..  ? 
1 - debuginfos yes or no ? epel ? and updates-testing ? 

[1]
https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_free-rawhide-template
https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_free-epel-template
https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_free-stable-template

**Comment by kwizart** [comment]
override -> no and there is no plan because unsigned fedora/rpmfusion packages might end there.
rawhide -> no, but that might be fixed at a later time (like way later).
stables, epel, debuginfo, source, updates-testing -> yes (signing process occurs between candidate -> testing).

**Comment by sergiomb2** [comment]
Also to review: 

https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_free-branched-template
https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_nonfree-branched-template
https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_nonfree-epel-template
https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_nonfree-rawhide-template
https://github.com/rpmfusion-infra/mock-rpmfusion/blob/master/rpmfusion_nonfree-stable-template

**Comment by kwizart** [comment]
debuginfo are missing gpgcheck along rawhide repos that are signed nowadays.
only repo missing gpg are override, but mainly because the content there might comes from various repository (mainly fedora, or centos/epel).
