### ISSUE TITLE
updates disabled but updates-testing enabled for F28

### ISSUE THREAD

**Issue by xavierba** [rpmfusion-infra/mock-rpmfusion#14]
The F28 mock configs for both free and nonfree have the updates repo disabled and the updates-testing repo enabled.
This commit needs to be reverted: https://github.com/rpmfusion-infra/mock-rpmfusion/commit/2364cced202a533eb5730e887002a2de38f2d800

**Comment by sergiomb2** [comment]
oops , I forgot update mock config for F28 GA , I will fix that soon .

**Comment by sergiomb2** [comment]
I built mock-rpmfusion-free-28.1-1.fc28 and mock-rpmfusion-free-28.1-1.fc29 , can you give it a test ? 
what version/branch do you like to test ?

**Comment by sergiomb2** [comment]
OK I built it for el7 
http://koji.rpmfusion.org/koji/buildinfo?buildID=7614

**Comment by xavierba** [comment]
There'a a typo on the version in the changelog:
```* Fri Jun 01 2018 Sérgio Basto <sergio@serjux.com> - 18.1-1```
Otherwise, looks good.

**Comment by sergiomb2** [comment]
thanks for the feedback
